    - name: install php,mysql-php
      yum: name={{item}} state=present
      with_items:
      - php
      - php-mysql

#    - name: add write loadmodule for using php file
#      lineinfile: insertafter='# LoadModule foo_module modules/mod_foo.so'  dest=/etc/httpd/conf/httpd.conf line={{item}} mode=0755
#      with_items:
#      - 'AddType text/html .php .html'
#      - 'AddHandler php5-script .php'
#      - 'LoadModule php5_module        modules/libphp5.so'

